### PR TITLE
WIP refactor dynamic theme

### PR DESCRIPTION
**Pull request by aplyd**

### CODE REVIEW

**Comment by aplyd** [comment]
@nickadamson holy merge conflicts. going to need to pair with you to resolve them.

**Comment by leojin** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
master-g, @adambalogh, @tranduybau, @zpjayyy, @wang-yi-bit64, @rpedroni, @xxxijustwei, @yiming-face, @tohere, @macelai, @Carlos-RealT, @wvfrm, @kyantran280912, @devpavan04, @devinhalladay, @xnng, @Niko030303, @3scava1i3r, @skyve2012, @ja88a

**Comment by tranduybau** [comment]
Hi @aplyd 
IDK why but when installing github package for Raycast, it said this PR is belonged to me :( 

I saw you don't need this one anymore right? Can you cancel it?

**Comment by aplyd** [comment]
@tranduybau weird. no problem.

**Comment by aplyd** [comment]
@tranduybau can you link the raycast package repo?

**Comment by tranduybau** [comment]
https://github.com/raycast/extensions/tree/e9f6b19f08f51c2850cd93851ef7bd69dd987bc6/extensions/github

Here is the package, When I installed it, It said that someone mentioned me on this PR :D funny

**Comment by tranduybau** [comment]
@aplyd funny that it is not removed 😆 
Screenshot 2024-03-08 at 10 48 22 PM

**Comment by tranduybau** [comment]
Screenshot 2024-03-13 at 2 28 27 PM


Turn out not the package, it's github problem. Thank for closing the PR :D I will ignore this one :(

**Pull request closed without merging**
